
var dfreader = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(dfreader) {
  dfreader = dfreader || {};


var h;h||(h=typeof dfreader !== 'undefined' ? dfreader : {});var aa,ca;h.ready=new Promise(function(a,b){aa=a;ca=b});var da=Object.assign({},h),ea="./this.program",fa="object"==typeof window,ha="function"==typeof importScripts,r="",ia,ja,ka,fs,la,ma;
if("object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node)r=ha?require("path").dirname(r)+"/":__dirname+"/",ma=()=>{la||(fs=require("fs"),la=require("path"))},ia=function(a,b){ma();a=la.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},ka=a=>{a=ia(a,!0);a.buffer||(a=new Uint8Array(a));return a},ja=(a,b,c)=>{ma();a=la.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),
process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",function(a){throw a;}),h.inspect=function(){return"[Emscripten Module object]"};else if(fa||ha)ha?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src),_scriptDir&&(r=_scriptDir),0!==r.indexOf("blob:")?r=r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1):r="",ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(ka=a=>{var b=
new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var na=h.print||console.log.bind(console),t=h.printErr||console.warn.bind(console);Object.assign(h,da);da=null;h.thisProgram&&(ea=h.thisProgram);var u=0,oa;h.wasmBinary&&(oa=h.wasmBinary);
var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&v("no native wasm support detected");var pa,qa=!1,ra="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function y(a,b){return a?sa(A,a,b):""}
function ta(a,b,c,d){if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|f>>12}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0}}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var va="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function wa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&xa[c];)++c;c<<=1;if(32<c-a&&va)return va.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=B[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function ya(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;return b-d}function za(a){return 2*a.length}function Aa(a,b){for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ba(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d}function Ca(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var Da,E,A,B,xa,C,F,Ea,Fa;
function Ga(){var a=pa.buffer;Da=a;h.HEAP8=E=new Int8Array(a);h.HEAP16=B=new Int16Array(a);h.HEAP32=C=new Int32Array(a);h.HEAPU8=A=new Uint8Array(a);h.HEAPU16=xa=new Uint16Array(a);h.HEAPU32=F=new Uint32Array(a);h.HEAPF32=Ea=new Float32Array(a);h.HEAPF64=Fa=new Float64Array(a)}var Ha,Ia=[],Ja=[],Ka=[];function La(){var a=h.preRun.shift();Ia.unshift(a)}var G=0,Ma=null,Na=null;
function v(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";t(a);qa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ca(a);throw a;}function Oa(){return H.startsWith("data:application/octet-stream;base64,")}var H;H="dfreader_wasm.f029c5c.wasm";if(!Oa()){var Pa=H;H=h.locateFile?h.locateFile(Pa,r):r+Pa}function Qa(){var a=H;try{if(a==H&&oa)return new Uint8Array(oa);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}catch(b){v(b)}}
function Ra(){if(!oa&&(fa||ha)){if("function"==typeof fetch&&!H.startsWith("file://"))return fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return Qa()});if(ja)return new Promise(function(a,b){ja(H,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Qa()})}
function Sa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.hc;"number"==typeof c?void 0===b.Ab?I(c)():I(c)(b.Ab):c(void 0===b.Ab?null:b.Ab)}}}function I(a){return Ha.get(a)}var Ta=[],Ua=0,J=0;
function K(a){this.tb=a;this.ab=a-24;this.Wb=function(b){F[this.ab+4>>2]=b};this.rb=function(){return F[this.ab+4>>2]};this.Tb=function(b){F[this.ab+8>>2]=b};this.Sb=function(){return F[this.ab+8>>2]};this.Ub=function(){C[this.ab>>2]=0};this.Db=function(b){E[this.ab+12>>0]=b?1:0};this.Nb=function(){return 0!=E[this.ab+12>>0]};this.Eb=function(b){E[this.ab+13>>0]=b?1:0};this.Hb=function(){return 0!=E[this.ab+13>>0]};this.Pb=function(b,c){this.sb(0);this.Wb(b);this.Tb(c);this.Ub();this.Db(!1);this.Eb(!1)};
this.Jb=function(){C[this.ab>>2]+=1};this.ac=function(){var b=C[this.ab>>2];C[this.ab>>2]=b-1;return 1===b};this.sb=function(b){F[this.ab+16>>2]=b};this.Kb=function(){return F[this.ab+16>>2]};this.Ob=function(){if(Va(this.rb()))return F[this.tb>>2];var b=this.Kb();return 0!==b?b:this.tb}}function Wa(a){return M((new K(a)).ab)}function Xa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ya=void 0;
function N(a){for(var b="";A[a];)b+=Ya[A[a++]];return b}var O={},P={},Za={};function $a(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function ab(a,b){a=$a(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function bb(a){var b=Error,c=ab(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var cb=void 0;function Q(a){throw new cb(a);}var db=void 0;function eb(a){throw new db(a);}
function R(a,b,c){function d(l){l=c(l);l.length!==a.length&&eb("Mismatched type converter count");for(var m=0;m<a.length;++m)S(a[m],l[m])}a.forEach(function(l){Za[l]=b});var e=Array(b.length),f=[],k=0;b.forEach((l,m)=>{P.hasOwnProperty(l)?e[m]=P[l]:(f.push(l),O.hasOwnProperty(l)||(O[l]=[]),O[l].push(()=>{e[m]=P[l];++k;k===f.length&&d(e)}))});0===f.length&&d(e)}
function S(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Q('type "'+d+'" must have a positive integer typeid pointer');if(P.hasOwnProperty(a)){if(c.Vb)return;Q("Cannot register type '"+d+"' twice")}P[a]=b;delete Za[a];O.hasOwnProperty(a)&&(b=O[a],delete O[a],b.forEach(e=>e()))}function fb(a){Q(a.$a.cb.bb.name+" instance already deleted")}var gb=!1;function hb(){}
function ib(a){--a.count.value;0===a.count.value&&(a.fb?a.gb.lb(a.fb):a.cb.bb.lb(a.ab))}function jb(a,b,c){if(b===c)return a;if(void 0===c.hb)return null;a=jb(a,b,c.hb);return null===a?null:c.Mb(a)}var kb={},lb=[];function mb(){for(;lb.length;){var a=lb.pop();a.$a.pb=!1;a["delete"]()}}var nb=void 0,ob={};function pb(a,b){for(void 0===b&&Q("ptr should not be undefined");a.hb;)b=a.vb(b),a=a.hb;return ob[b]}
function qb(a,b){b.cb&&b.ab||eb("makeClassHandle requires ptr and ptrType");!!b.gb!==!!b.fb&&eb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return rb(Object.create(a,{$a:{value:b}}))}function rb(a){if("undefined"===typeof FinalizationRegistry)return rb=b=>b,a;gb=new FinalizationRegistry(b=>{ib(b.$a)});rb=b=>{var c=b.$a;c.fb&&gb.register(b,{$a:c},b);return b};hb=b=>{gb.unregister(b)};return rb(a)}function T(){}
function sb(a,b,c){if(void 0===a[b].eb){var d=a[b];a[b]=function(){a[b].eb.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].eb+")!");return a[b].eb[arguments.length].apply(this,arguments)};a[b].eb=[];a[b].eb[d.ob]=d}}
function tb(a,b){h.hasOwnProperty(a)?(Q("Cannot register public name '"+a+"' twice"),sb(h,a,a),h.hasOwnProperty(void 0)&&Q("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),h[a].eb[void 0]=b):h[a]=b}function ub(a,b,c,d,e,f,k,l){this.name=a;this.constructor=b;this.qb=c;this.lb=d;this.hb=e;this.Qb=f;this.vb=k;this.Mb=l;this.Yb=[]}
function vb(a,b,c){for(;b!==c;)b.vb||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.vb(a),b=b.hb;return a}function wb(a,b){if(null===b)return this.Bb&&Q("null is not a valid "+this.name),0;b.$a||Q('Cannot pass "'+xb(b)+'" as a '+this.name);b.$a.ab||Q("Cannot pass deleted object as a pointer of type "+this.name);return vb(b.$a.ab,b.$a.cb.bb,this.bb)}
function yb(a,b){if(null===b){this.Bb&&Q("null is not a valid "+this.name);if(this.xb){var c=this.Zb();null!==a&&a.push(this.lb,c);return c}return 0}b.$a||Q('Cannot pass "'+xb(b)+'" as a '+this.name);b.$a.ab||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.wb&&b.$a.cb.wb&&Q("Cannot convert argument of type "+(b.$a.gb?b.$a.gb.name:b.$a.cb.name)+" to parameter type "+this.name);c=vb(b.$a.ab,b.$a.cb.bb,this.bb);if(this.xb)switch(void 0===b.$a.fb&&Q("Passing raw pointer to smart pointer is illegal"),
this.bc){case 0:b.$a.gb===this?c=b.$a.fb:Q("Cannot convert argument of type "+(b.$a.gb?b.$a.gb.name:b.$a.cb.name)+" to parameter type "+this.name);break;case 1:c=b.$a.fb;break;case 2:if(b.$a.gb===this)c=b.$a.fb;else{var d=b.clone();c=this.$b(c,zb(function(){d["delete"]()}));null!==a&&a.push(this.lb,c)}break;default:Q("Unsupporting sharing policy")}return c}
function Ab(a,b){if(null===b)return this.Bb&&Q("null is not a valid "+this.name),0;b.$a||Q('Cannot pass "'+xb(b)+'" as a '+this.name);b.$a.ab||Q("Cannot pass deleted object as a pointer of type "+this.name);b.$a.cb.wb&&Q("Cannot convert argument of type "+b.$a.cb.name+" to parameter type "+this.name);return vb(b.$a.ab,b.$a.cb.bb,this.bb)}function Bb(a){return this.fromWireType(F[a>>2])}
function U(a,b,c,d){this.name=a;this.bb=b;this.Bb=c;this.wb=d;this.xb=!1;this.lb=this.$b=this.Zb=this.Ib=this.bc=this.Xb=void 0;void 0!==b.hb?this.toWireType=yb:(this.toWireType=d?wb:Ab,this.jb=null)}function Cb(a,b){h.hasOwnProperty(a)||eb("Replacing nonexistant public symbol");h[a]=b;h[a].ob=void 0}
function Db(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=h["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=I(b).apply(null,c);return d}}function V(a,b){a=N(a);var c=a.includes("j")?Db(a,b):I(b);"function"!=typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var Eb=void 0;function Fb(a){a=Gb(a);var b=N(a);M(a);return b}
function Jb(a,b){function c(f){e[f]||P[f]||(Za[f]?Za[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Eb(a+": "+d.map(Fb).join([", "]));}function Kb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=ab(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}function Lb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Mb(a,b,c,d,e){var f=b.length;2>f&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].jb){l=!0;break}var m="void"!==b[0].name,n="",p="";for(c=0;c<f-2;++c)n+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+$a(a)+"("+n+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var w=l?"destructors":"null";n="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[Q,d,e,Lb,b[0],b[1]];k&&(a+="var thisWired = classParam.toWireType("+w+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+w+", arg"+c+"); // "+b[c+2].name+"\n",n.push("argType"+c),d.push(b[c+2]);k&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(m?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=k?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].jb&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",n.push(f+"_dtor"),d.push(b[c].jb));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");n.push(a+"}\n");return Kb(n).apply(null,d)}function Nb(a,b){for(var c=[],d=0;d<a;d++)c.push(C[(b>>2)+d]);return c}var Ob=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Pb(a){4<a&&0===--W[a].Cb&&(W[a]=void 0,Ob.push(a))}
var zb=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ob.length?Ob.pop():W.length;W[b]={Cb:1,value:a};return b}};function xb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Qb(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ea[c>>2])};case 3:return function(c){return this.fromWireType(Fa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Rb(a,b,c){switch(b){case 0:return c?function(d){return E[d]}:function(d){return A[d]};case 1:return c?function(d){return B[d>>1]}:function(d){return xa[d>>1]};case 2:return c?function(d){return C[d>>2]}:function(d){return F[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Sb={};
function Tb(){if(!Ub){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Sb)void 0===Sb[b]?delete a[b]:a[b]=Sb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ub=c}return Ub}var Ub,Vb=[null,[],[]];function Wb(a){return 0===a%4&&(0!==a%100||0===a%400)}
var Xb=[31,29,31,30,31,30,31,31,30,31,30,31],Yb=[31,28,31,30,31,30,31,31,30,31,30,31];
function Zb(a,b,c,d){function e(g,q,z){for(g="number"==typeof g?g.toString():g||"";g.length<q;)g=z[0]+g;return g}function f(g,q){return e(g,q,"0")}function k(g,q){function z(L){return 0>L?-1:0<L?1:0}var D;0===(D=z(g.getFullYear()-q.getFullYear()))&&0===(D=z(g.getMonth()-q.getMonth()))&&(D=z(g.getDate()-q.getDate()));return D}function l(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),
0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function m(g){var q=g.mb;for(g=new Date((new Date(g.nb+1900,0,1)).getTime());0<q;){var z=g.getMonth(),D=(Wb(g.getFullYear())?Xb:Yb)[z];if(q>D-g.getDate())q-=D-g.getDate()+1,g.setDate(1),11>z?g.setMonth(z+1):(g.setMonth(0),g.setFullYear(g.getFullYear()+1));else{g.setDate(g.getDate()+q);break}}z=new Date(g.getFullYear()+1,0,4);q=l(new Date(g.getFullYear(),
0,4));z=l(z);return 0>=k(q,g)?0>=k(z,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var n=C[d+40>>2];d={ec:C[d>>2],dc:C[d+4>>2],yb:C[d+8>>2],Fb:C[d+12>>2],zb:C[d+16>>2],nb:C[d+20>>2],ib:C[d+24>>2],mb:C[d+28>>2],jc:C[d+32>>2],cc:C[d+36>>2],fc:n?y(n):""};c=y(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in n)c=c.replace(new RegExp(p,"g"),n[p]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),x="January February March April May June July August September October November December".split(" ");n={"%a":function(g){return w[g.ib].substring(0,3)},"%A":function(g){return w[g.ib]},"%b":function(g){return x[g.zb].substring(0,3)},"%B":function(g){return x[g.zb]},
"%C":function(g){return f((g.nb+1900)/100|0,2)},"%d":function(g){return f(g.Fb,2)},"%e":function(g){return e(g.Fb,2," ")},"%g":function(g){return m(g).toString().substring(2)},"%G":function(g){return m(g)},"%H":function(g){return f(g.yb,2)},"%I":function(g){g=g.yb;0==g?g=12:12<g&&(g-=12);return f(g,2)},"%j":function(g){for(var q=0,z=0;z<=g.zb-1;q+=(Wb(g.nb+1900)?Xb:Yb)[z++]);return f(g.Fb+q,3)},"%m":function(g){return f(g.zb+1,2)},"%M":function(g){return f(g.dc,2)},"%n":function(){return"\n"},"%p":function(g){return 0<=
g.yb&&12>g.yb?"AM":"PM"},"%S":function(g){return f(g.ec,2)},"%t":function(){return"\t"},"%u":function(g){return g.ib||7},"%U":function(g){return f(Math.floor((g.mb+7-g.ib)/7),2)},"%V":function(g){var q=Math.floor((g.mb+7-(g.ib+6)%7)/7);2>=(g.ib+371-g.mb-2)%7&&q++;if(q)53==q&&(z=(g.ib+371-g.mb)%7,4==z||3==z&&Wb(g.nb)||(q=1));else{q=52;var z=(g.ib+7-g.mb-1)%7;(4==z||5==z&&Wb(g.nb%400-1))&&q++}return f(q,2)},"%w":function(g){return g.ib},"%W":function(g){return f(Math.floor((g.mb+7-(g.ib+6)%7)/7),2)},
"%y":function(g){return(g.nb+1900).toString().substring(2)},"%Y":function(g){return g.nb+1900},"%z":function(g){g=g.cc;var q=0<=g;g=Math.abs(g)/60;return(q?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":function(g){return g.fc},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(p in n)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),n[p](d)));c=c.replace(/\0\0/g,"%");p=$b(c);if(p.length>b)return 0;E.set(p,a);return p.length-1}for(var ac=Array(256),bc=0;256>bc;++bc)ac[bc]=String.fromCharCode(bc);
Ya=ac;cb=h.BindingError=bb("BindingError");db=h.InternalError=bb("InternalError");T.prototype.isAliasOf=function(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.$a.cb.bb,c=this.$a.ab,d=a.$a.cb.bb;for(a=a.$a.ab;b.hb;)c=b.vb(c),b=b.hb;for(;d.hb;)a=d.vb(a),d=d.hb;return b===d&&c===a};
T.prototype.clone=function(){this.$a.ab||fb(this);if(this.$a.ub)return this.$a.count.value+=1,this;var a=rb,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.$a;a=a(c.call(b,d,{$a:{value:{count:e.count,pb:e.pb,ub:e.ub,ab:e.ab,cb:e.cb,fb:e.fb,gb:e.gb}}}));a.$a.count.value+=1;a.$a.pb=!1;return a};T.prototype["delete"]=function(){this.$a.ab||fb(this);this.$a.pb&&!this.$a.ub&&Q("Object already scheduled for deletion");hb(this);ib(this.$a);this.$a.ub||(this.$a.fb=void 0,this.$a.ab=void 0)};
T.prototype.isDeleted=function(){return!this.$a.ab};T.prototype.deleteLater=function(){this.$a.ab||fb(this);this.$a.pb&&!this.$a.ub&&Q("Object already scheduled for deletion");lb.push(this);1===lb.length&&nb&&nb(mb);this.$a.pb=!0;return this};h.getInheritedInstanceCount=function(){return Object.keys(ob).length};h.getLiveInheritedInstances=function(){var a=[],b;for(b in ob)ob.hasOwnProperty(b)&&a.push(ob[b]);return a};h.flushPendingDeletes=mb;h.setDelayFunction=function(a){nb=a;lb.length&&nb&&nb(mb)};
U.prototype.Rb=function(a){this.Ib&&(a=this.Ib(a));return a};U.prototype.Gb=function(a){this.lb&&this.lb(a)};U.prototype.argPackAdvance=8;U.prototype.readValueFromPointer=Bb;U.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
U.prototype.fromWireType=function(a){function b(){return this.xb?qb(this.bb.qb,{cb:this.Xb,ab:c,gb:this,fb:a}):qb(this.bb.qb,{cb:this,ab:a})}var c=this.Rb(a);if(!c)return this.Gb(a),null;var d=pb(this.bb,c);if(void 0!==d){if(0===d.$a.count.value)return d.$a.ab=c,d.$a.fb=a,d.clone();d=d.clone();this.Gb(a);return d}d=this.bb.Qb(c);d=kb[d];if(!d)return b.call(this);d=this.wb?d.Lb:d.pointerType;var e=jb(c,this.bb,d.bb);return null===e?b.call(this):this.xb?qb(d.bb.qb,{cb:d,ab:e,gb:this,fb:a}):qb(d.bb.qb,
{cb:d,ab:e})};Eb=h.UnboundTypeError=bb("UnboundTypeError");h.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};h.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};function $b(a){var b=Array(ua(a)+1);ta(a,b,0,b.length);return b}
var Vc={l:function(a,b,c,d){v("Assertion failed: "+y(a)+", at: "+[b?y(b):"unknown filename",c,d?y(d):"unknown function"])},m:function(a){return cc(a+24)+24},u:function(a){a=new K(a);a.Nb()||(a.Db(!0),Ua--);a.Eb(!1);Ta.push(a);a.Jb();return a.Ob()},A:function(){X(0);var a=Ta.pop();if(a.ac()&&!a.Hb()){var b=a.Sb();b&&I(b)(a.tb);Wa(a.tb)}J=0},b:function(){var a=J;if(!a)return u=0;var b=new K(a);b.sb(a);var c=b.rb();if(!c)return u=0,a;for(var d=Array.prototype.slice.call(arguments),e=0;e<d.length;e++){var f=
d[e];if(0===f||f===c)break;if(dc(f,c,b.ab+16))return u=f,a}u=c;return a},g:function(){var a=J;if(!a)return u=0;var b=new K(a);b.sb(a);var c=b.rb();if(!c)return u=0,a;for(var d=Array.prototype.slice.call(arguments),e=0;e<d.length;e++){var f=d[e];if(0===f||f===c)break;if(dc(f,c,b.ab+16))return u=f,a}u=c;return a},x:function(){var a=J;if(!a)return u=0;var b=new K(a);b.sb(a);var c=b.rb();if(!c)return u=0,a;for(var d=Array.prototype.slice.call(arguments),e=0;e<d.length;e++){var f=d[e];if(0===f||f===c)break;
if(dc(f,c,b.ab+16))return u=f,a}u=c;return a},q:function(){var a=J;if(!a)return u=0;var b=new K(a);b.sb(a);var c=b.rb();if(!c)return u=0,a;for(var d=Array.prototype.slice.call(arguments),e=0;e<d.length;e++){var f=d[e];if(0===f||f===c)break;if(dc(f,c,b.ab+16))return u=f,a}u=c;return a},p:Wa,ea:function(){var a=Ta.pop();a||v("no exception to throw");var b=a.tb;a.Hb()||(Ta.push(a),a.Eb(!0),a.Db(!1),Ua++);J=b;throw b;},o:function(a,b,c){(new K(a)).Pb(b,c);J=a;Ua++;throw a;},pa:function(){return Ua},d:function(a){J||
(J=a);throw a;},ia:function(){},va:function(a,b,c,d,e){var f=Xa(c);b=N(b);S(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var l=E;else if(2===c)l=B;else if(4===c)l=C;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[k>>f])},jb:null})},Fa:function(a,b,c,d,e,f,k,l,m,n,p,w,x){p=N(p);f=V(e,f);l&&(l=V(k,l));n&&(n=V(m,n));x=V(w,x);var g=$a(p);tb(g,function(){Jb("Cannot construct "+
p+" due to unbound types",[d])});R([a,b,c],d?[d]:[],function(q){q=q[0];if(d){var z=q.bb;var D=z.qb}else D=T.prototype;q=ab(g,function(){if(Object.getPrototypeOf(this)!==L)throw new cb("Use 'new' to construct "+p);if(void 0===ba.kb)throw new cb(p+" has no accessible constructor");var Hb=ba.kb[arguments.length];if(void 0===Hb)throw new cb("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(ba.kb).toString()+") parameters instead!");return Hb.apply(this,
arguments)});var L=Object.create(D,{constructor:{value:q}});q.prototype=L;var ba=new ub(p,q,L,x,z,f,l,n);z=new U(p,ba,!0,!1);D=new U(p+"*",ba,!1,!1);var Ib=new U(p+" const*",ba,!1,!0);kb[a]={pointerType:D,Lb:Ib};Cb(g,q);return[z,D,Ib]})},Ea:function(a,b,c,d,e,f,k){var l=Nb(c,d);b=N(b);f=V(e,f);R([],[a],function(m){function n(){Jb("Cannot call "+p+" due to unbound types",l)}m=m[0];var p=m.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var w=m.bb.constructor;void 0===w[b]?(n.ob=c-1,w[b]=
n):(sb(w,b,p),w[b].eb[c-1]=n);R([],l,function(x){x=[x[0],null].concat(x.slice(1));x=Mb(p,x,null,f,k);void 0===w[b].eb?(x.ob=c-1,w[b]=x):w[b].eb[c-1]=x;return[]});return[]})},Da:function(a,b,c,d,e,f){0<b||v();var k=Nb(b,c);e=V(d,e);R([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.bb.kb&&(l.bb.kb=[]);if(void 0!==l.bb.kb[b-1])throw new cb("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");
l.bb.kb[b-1]=()=>{Jb("Cannot construct "+l.name+" due to unbound types",k)};R([],k,function(n){n.splice(1,0,null);l.bb.kb[b-1]=Mb(m,n,null,e,f);return[]});return[]})},K:function(a,b,c,d,e,f,k,l){var m=Nb(c,d);b=N(b);f=V(e,f);R([],[a],function(n){function p(){Jb("Cannot call "+w+" due to unbound types",m)}n=n[0];var w=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&n.bb.Yb.push(b);var x=n.bb.qb,g=x[b];void 0===g||void 0===g.eb&&g.className!==n.name&&g.ob===c-2?(p.ob=c-2,p.className=
n.name,x[b]=p):(sb(x,b,w),x[b].eb[c-2]=p);R([],m,function(q){q=Mb(w,q,n,f,k);void 0===x[b].eb?(q.ob=c-2,x[b]=q):x[b].eb[c-2]=q;return[]});return[]})},ua:function(a,b){b=N(b);S(a,{name:b,fromWireType:function(c){c||Q("Cannot use deleted val. handle = "+c);var d=W[c].value;Pb(c);return d},toWireType:function(c,d){return zb(d)},argPackAdvance:8,readValueFromPointer:Bb,jb:null})},ba:function(a,b,c){c=Xa(c);b=N(b);S(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,
readValueFromPointer:Qb(b,c),jb:null})},E:function(a,b,c,d,e){b=N(b);-1===e&&(e=4294967295);e=Xa(c);var f=l=>l;if(0===d){var k=32-8*c;f=l=>l<<k>>>k}c=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};S(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:Rb(b,e,0!==d),jb:null})},z:function(a,b,c){function d(f){f>>=2;var k=F;return new e(Da,k[f+1],k[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];
c=N(c);S(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Vb:!0})},aa:function(a,b){b=N(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(d){var e=F[d>>2];if(c)for(var f=d+4,k=0;k<=e;++k){var l=d+4+k;if(k==e||0==A[l]){f=y(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(k=0;k<e;++k)m[k]=String.fromCharCode(A[d+4+k]);m=m.join("")}M(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==
typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||Q("Cannot pass non-string to std::string");var k=(c&&f?()=>ua(e):()=>e.length)(),l=cc(4+k+1);F[l>>2]=k;if(c&&f)ta(e,A,l+4,k+1);else if(f)for(f=0;f<k;++f){var m=e.charCodeAt(f);255<m&&(M(l),Q("String has UTF-16 code units that do not fit in 8 bits"));A[l+4+f]=m}else for(f=0;f<k;++f)A[l+4+f]=e[f];null!==d&&d.push(M,l);return l},argPackAdvance:8,readValueFromPointer:Bb,jb:function(d){M(d)}})},S:function(a,b,
c){c=N(c);if(2===b){var d=wa;var e=ya;var f=za;var k=()=>xa;var l=1}else 4===b&&(d=Aa,e=Ba,f=Ca,k=()=>F,l=2);S(a,{name:c,fromWireType:function(m){for(var n=F[m>>2],p=k(),w,x=m+4,g=0;g<=n;++g){var q=m+4+g*b;if(g==n||0==p[q>>l])x=d(x,q-x),void 0===w?w=x:(w+=String.fromCharCode(0),w+=x),x=q+b}M(m);return w},toWireType:function(m,n){"string"!=typeof n&&Q("Cannot pass non-string to C++ string type "+c);var p=f(n),w=cc(4+p+b);F[w>>2]=p>>l;e(n,w+4,p+b);null!==m&&m.push(M,w);return w},argPackAdvance:8,readValueFromPointer:Bb,
jb:function(m){M(m)}})},wa:function(a,b){b=N(b);S(a,{ic:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},R:function(){return Date.now()},Ba:Pb,Ca:function(a){4<a&&(W[a].Cb+=1)},X:function(a,b){var c=P[a];void 0===c&&Q("_emval_take_value has unknown type "+Fb(a));a=c;a=a.readValueFromPointer(b);return zb(a)},Q:function(){v("")},ta:function(a,b,c){A.copyWithin(a,b,b+c)},qa:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/
c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);e=e.min.call(e,2147483648,d+(65536-d%65536)%65536);a:{try{pa.grow(e-Da.byteLength+65535>>>16);Ga();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},na:function(a,b){var c=0;Tb().forEach(function(d,e){var f=b+c;e=F[a+4*e>>2]=f;for(f=0;f<d.length;++f)E[e++>>0]=d.charCodeAt(f);E[e>>0]=0;c+=d.length+1});return 0},oa:function(a,b){var c=Tb();F[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});F[b>>2]=d;return 0},ra:function(){return 52},
sa:function(){return 52},ha:function(){return 70},$:function(a,b,c,d){for(var e=0,f=0;f<c;f++){var k=F[b>>2],l=F[b+4>>2];b+=8;for(var m=0;m<l;m++){var n=A[k+m],p=Vb[a];0===n||10===n?((1===a?na:t)(sa(p,0)),p.length=0):p.push(n)}e+=l}F[d>>2]=e;return 0},a:function(){return u},O:ec,G:fc,Y:gc,za:hc,Z:ic,t:jc,f:kc,N:lc,xa:mc,B:nc,c:oc,Aa:pc,ca:qc,V:rc,i:sc,W:tc,k:uc,_:vc,y:wc,v:xc,D:yc,C:zc,H:Ac,M:Bc,ga:Cc,ka:Dc,ja:Ec,fa:Fc,n:Gc,s:Hc,e:Ic,h:Jc,ya:Kc,j:Lc,U:Mc,r:Nc,F:Oc,w:Pc,da:Qc,T:Rc,J:Sc,L:Tc,la:Uc,
I:function(a){return a},P:function(a){u=a},ma:function(a,b,c,d){return Zb(a,b,c,d)}};
(function(){function a(e){h.asm=e.exports;pa=h.asm.Ga;Ga();Ha=h.asm.Ja;Ja.unshift(h.asm.Ha);G--;h.monitorRunDependencies&&h.monitorRunDependencies(G);0==G&&(null!==Ma&&(clearInterval(Ma),Ma=null),Na&&(e=Na,Na=null,e()))}function b(e){a(e.instance)}function c(e){return Ra().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){t("failed to asynchronously prepare wasm: "+f);v(f)})}var d={a:Vc};G++;h.monitorRunDependencies&&h.monitorRunDependencies(G);
if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return t("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return oa||"function"!=typeof WebAssembly.instantiateStreaming||Oa()||H.startsWith("file://")||"function"!=typeof fetch?c(b):fetch(H,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){t("wasm streaming compile failed: "+f);t("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ca);
return{}})();h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm.Ha).apply(null,arguments)};var cc=h._malloc=function(){return(cc=h._malloc=h.asm.Ia).apply(null,arguments)},M=h._free=function(){return(M=h._free=h.asm.Ka).apply(null,arguments)},Gb=h.___getTypeName=function(){return(Gb=h.___getTypeName=h.asm.La).apply(null,arguments)};h.___embind_register_native_and_builtin_types=function(){return(h.___embind_register_native_and_builtin_types=h.asm.Ma).apply(null,arguments)};
var X=h._setThrew=function(){return(X=h._setThrew=h.asm.Na).apply(null,arguments)},Y=h.stackSave=function(){return(Y=h.stackSave=h.asm.Oa).apply(null,arguments)},Z=h.stackRestore=function(){return(Z=h.stackRestore=h.asm.Pa).apply(null,arguments)},dc=h.___cxa_can_catch=function(){return(dc=h.___cxa_can_catch=h.asm.Qa).apply(null,arguments)},Va=h.___cxa_is_pointer_type=function(){return(Va=h.___cxa_is_pointer_type=h.asm.Ra).apply(null,arguments)},Wc=h.dynCall_viji=function(){return(Wc=h.dynCall_viji=
h.asm.Sa).apply(null,arguments)},Xc=h.dynCall_iij=function(){return(Xc=h.dynCall_iij=h.asm.Ta).apply(null,arguments)},Yc=h.dynCall_jiii=function(){return(Yc=h.dynCall_jiii=h.asm.Ua).apply(null,arguments)};h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.Va).apply(null,arguments)};var Zc=h.dynCall_iiiiij=function(){return(Zc=h.dynCall_iiiiij=h.asm.Wa).apply(null,arguments)};h.dynCall_viijii=function(){return(h.dynCall_viijii=h.asm.Xa).apply(null,arguments)};
var $c=h.dynCall_jiiii=function(){return($c=h.dynCall_jiiii=h.asm.Ya).apply(null,arguments)};h.dynCall_iiiiijj=function(){return(h.dynCall_iiiiijj=h.asm.Za).apply(null,arguments)};h.dynCall_iiiiiijj=function(){return(h.dynCall_iiiiiijj=h.asm._a).apply(null,arguments)};function oc(a,b,c){var d=Y();try{return I(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function Hc(a,b){var c=Y();try{I(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;X(1,0)}}
function sc(a,b,c,d){var e=Y();try{return I(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function kc(a,b){var c=Y();try{return I(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;X(1,0)}}function uc(a,b,c,d,e){var f=Y();try{return I(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0)throw k;X(1,0)}}function Ic(a,b,c){var d=Y();try{I(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function Jc(a,b,c,d){var e=Y();try{I(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}
function pc(a,b,c,d){var e=Y();try{return I(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function xc(a,b,c,d,e,f,k){var l=Y();try{return I(a)(b,c,d,e,f,k)}catch(m){Z(l);if(m!==m+0)throw m;X(1,0)}}function Lc(a,b,c,d,e){var f=Y();try{I(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0)throw k;X(1,0)}}function Gc(a){var b=Y();try{I(a)()}catch(c){Z(b);if(c!==c+0)throw c;X(1,0)}}function Nc(a,b,c,d,e,f){var k=Y();try{I(a)(b,c,d,e,f)}catch(l){Z(k);if(l!==l+0)throw l;X(1,0)}}
function wc(a,b,c,d,e,f){var k=Y();try{return I(a)(b,c,d,e,f)}catch(l){Z(k);if(l!==l+0)throw l;X(1,0)}}function ec(a,b){var c=Y();try{return I(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;X(1,0)}}function lc(a,b,c){var d=Y();try{return I(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function hc(a,b){var c=Y();try{return I(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;X(1,0)}}function Ac(a,b,c,d,e,f,k,l,m,n,p){var w=Y();try{return I(a)(b,c,d,e,f,k,l,m,n,p)}catch(x){Z(w);if(x!==x+0)throw x;X(1,0)}}
function Oc(a,b,c,d,e,f,k){var l=Y();try{I(a)(b,c,d,e,f,k)}catch(m){Z(l);if(m!==m+0)throw m;X(1,0)}}function jc(a){var b=Y();try{return I(a)()}catch(c){Z(b);if(c!==c+0)throw c;X(1,0)}}function yc(a,b,c,d,e,f,k,l){var m=Y();try{return I(a)(b,c,d,e,f,k,l)}catch(n){Z(m);if(n!==n+0)throw n;X(1,0)}}function nc(a,b,c){var d=Y();try{return I(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function Kc(a,b,c,d,e,f,k){var l=Y();try{I(a)(b,c,d,e,f,k)}catch(m){Z(l);if(m!==m+0)throw m;X(1,0)}}
function tc(a,b,c,d,e){var f=Y();try{return I(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0)throw k;X(1,0)}}function Pc(a,b,c,d,e,f,k,l){var m=Y();try{I(a)(b,c,d,e,f,k,l)}catch(n){Z(m);if(n!==n+0)throw n;X(1,0)}}function zc(a,b,c,d,e,f,k,l,m){var n=Y();try{return I(a)(b,c,d,e,f,k,l,m)}catch(p){Z(n);if(p!==p+0)throw p;X(1,0)}}function rc(a,b,c,d,e,f,k,l){var m=Y();try{return I(a)(b,c,d,e,f,k,l)}catch(n){Z(m);if(n!==n+0)throw n;X(1,0)}}
function Qc(a,b,c,d,e,f,k,l,m){var n=Y();try{I(a)(b,c,d,e,f,k,l,m)}catch(p){Z(n);if(p!==p+0)throw p;X(1,0)}}function fc(a,b,c){var d=Y();try{return I(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function qc(a,b,c,d,e){var f=Y();try{return I(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0)throw k;X(1,0)}}function Mc(a,b,c,d,e,f){var k=Y();try{I(a)(b,c,d,e,f)}catch(l){Z(k);if(l!==l+0)throw l;X(1,0)}}
function Rc(a,b,c,d,e,f,k,l,m,n){var p=Y();try{I(a)(b,c,d,e,f,k,l,m,n)}catch(w){Z(p);if(w!==w+0)throw w;X(1,0)}}function mc(a,b,c,d){var e=Y();try{return I(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function vc(a,b,c,d,e,f){var k=Y();try{return I(a)(b,c,d,e,f)}catch(l){Z(k);if(l!==l+0)throw l;X(1,0)}}function ic(a,b,c,d){var e=Y();try{return I(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function gc(a,b,c,d){var e=Y();try{return I(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}
function Bc(a,b,c,d,e,f,k,l,m,n,p,w){var x=Y();try{return I(a)(b,c,d,e,f,k,l,m,n,p,w)}catch(g){Z(x);if(g!==g+0)throw g;X(1,0)}}function Sc(a,b,c,d,e,f,k,l,m,n,p){var w=Y();try{I(a)(b,c,d,e,f,k,l,m,n,p)}catch(x){Z(w);if(x!==x+0)throw x;X(1,0)}}function Tc(a,b,c,d,e,f,k,l,m,n,p,w,x,g,q,z){var D=Y();try{I(a)(b,c,d,e,f,k,l,m,n,p,w,x,g,q,z)}catch(L){Z(D);if(L!==L+0)throw L;X(1,0)}}function Uc(a,b,c,d,e){var f=Y();try{Wc(a,b,c,d,e)}catch(k){Z(f);if(k!==k+0)throw k;X(1,0)}}
function Dc(a,b,c,d){var e=Y();try{return Xc(a,b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function Ec(a,b,c,d){var e=Y();try{return Yc(a,b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function Cc(a,b,c,d,e,f,k){var l=Y();try{return Zc(a,b,c,d,e,f,k)}catch(m){Z(l);if(m!==m+0)throw m;X(1,0)}}function Fc(a,b,c,d,e){var f=Y();try{return $c(a,b,c,d,e)}catch(k){Z(f);if(k!==k+0)throw k;X(1,0)}}var ad;Na=function bd(){ad||cd();ad||(Na=bd)};
function cd(){function a(){if(!ad&&(ad=!0,h.calledRun=!0,!qa)){Sa(Ja);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();Ka.unshift(b)}Sa(Ka)}}if(!(0<G)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)La();Sa(Ia);0<G||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}h.run=cd;
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();cd();


  return dfreader.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = dfreader;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return dfreader; });
else if (typeof exports === 'object')
  exports["dfreader"] = dfreader;
